### ISSUE TITLE
Bug with Seasons 

### ISSUE THREAD

**Issue by OliverKullmann** [GtX-Andy/easyDevelopmentControls#1]
Hello, I just downloaded the mod Easy Development Controls and found a bug when playing with seasons. If you play with 2 or more days, it still stays at 1 per season even if you switch it. You can also change it in the menu, but it has a black background and you cannot look at it. Would be nice if someone can answer me and if it's just me like that help to fix it.

**Comment by GtX-Andy** [comment]
Hi, could you please confirm what feature you are talking about.

If this is the **Set Time** feature on the Environment page then the day in Season will only become available the next time the seasons changes.

This is the same with the Base Game, if the season length is changed the current season must first finish before it takes effect.

If this is not your issue then please provide a little more information so I can try and help 😄
