### ISSUE TITLE
Suggestion for Expansion of Feature for a Future Update

### ISSUE THREAD

**Issue by cwattyeso** [GtX-Andy/easyDevelopmentControls#12]
Hello GTX and thank you firstly for the great Easy Development Controls Mod and providing it once again to players. I've been really waiting for this mod since the game's release having found the mod in FS19 to be invaluable to me as a content creator.

One thing I have liked so far in the new Mod is the option to toggle on and enable the Delete Objects Input, that is letting me remove trees very easily on maps using the delete key, and especially some trees which the in game chainsaw and tools don't recognise meaning until now they have been unremoveable.

I would however like to see this feature expanded in a future update if possible to allow us to delete other objects on the map like decorations, posts, poles, fences, decorative buildings which have no function etc. Unless I'm missing something already I'm not able to delete any of these things with the Delete Objects Input, but would find it super helpful to have this expanded functionality.

I know in FS19 there was an Objects Hider Mod, but at the moment nothing like that exists for FS22, and to be honest the quick delete function provided by Easy Development Controls would definitely appeal to me more then having to run yet another mod to achieve the same goal.

**Comment by GtX-Andy** [comment]
Hey @cwattyeso  nice to see you around...

I am glad to hear you are enjoying the current release so far 😄 
The 'Delete Objects' is definitely useful and right up there with the 'Set Fill Level' feature working on a pallet so you can setup a nice role play or new save game with some partially full pallets.

In regards to the deleting of 'Map Objects' I will not say this is not going to happen however I am not sure it would be part of Easy Development Controls (EDC).

As EDC is originally a Mod Creator tool I try and limit overwriting functions or saving large amounts of data as this can cause conflicts with mods and then, well.... it is not good for testing 🤣

So the biggest issue is mainly the saving at this stage as a 'Map Object / Built In Object' is not saved in anyway by default as it is not required to move or hide itself normally. This means a lot of extra information for me to save and return and has potential to break game saves, not great again for a Dev tool 😁

I do like the idea of removing / hiding map objects and had given the idea some thought as far back as 15 but I never had time. I am sure if the creator of the mod in 19 does not wish to bring it to 22 I can look at this after I finish my current projects.. I just would not want to take their mod and make a new one if they are working on a new release as I hate when this happens to me and trust me it does a lot 🙄

Always happy to talk on Discord, or via Giants forums if you wish to discuss more....
