### ISSUE TITLE
Running settings not saved in multiplayer 

### ISSUE THREAD

**Issue by GtX-Andy** [GtX-Andy/easyDevelopmentControls#13]
Version: 1.0.0.0
Release Type: RELEASE 

***Note:  Reported by user outside of GitHub on GtX Discord channel***

Running multiplier and running On / Off is not loaded on server games

**Comment by GtX-Andy** [comment]
For release 1.0.0.0 this was ***by design***

Settings saved in SP are not synced to the clients as each user may have different needs.

I hoped to push an update tonight but due to another hectic day it has not been possible however it will be available tomorrow. I will look tonight at adding a 'Default Settings' file where these options can be configured and used for new save games and all MP games.

**Comment by Jayshua83** [comment]
This still doesn't work in the latest patch. The Multiplier saves but NOT the On/Off Toggle!
