### ISSUE TITLE
2022-05-07 15:36 Error: Running LUA method 'update'.

### ISSUE THREAD

**Issue by TheOnlyChappell** [GtX-Andy/easyDevelopmentControls#18]
wenn ich eine Map, die ich erneut laden will, öffne, schmeist der mir den Error. 

dataS/scripts/environment/EnvironmentTimeEvent.lua(48) : attempt to index local 'env' (a nil value)

habe deinen Mod entfernt und dann ging es wiede
[Error.txt](https://github.com/GtX-Andy/easyDevelopmentControls/files/8645307/Error.txt)
r

**Comment by GtX-Andy** [comment]
Thanks for the report, this is a known issue reported [HERE](https://github.com/GtX-Andy/easyDevelopmentControls/issues/8).

This is fixed in the current [Beta Release](https://github.com/GtX-Andy/easyDevelopmentControls/releases/tag/V1.0.1.0-beta)
