### ISSUE TITLE
Fill Level Limit please, please for LS22

### ISSUE THREAD

**Issue by Maag000** [GtX-Andy/easyDevelopmentControls#23]
Hi Andy
sorry for this issue but I dont't know how I can contact you in an other way.
Please can you write the Fill Level Limit script for LS22 please?
https://farming-simulator.com/mod.php?lang=de&country=be&mod_id=150303

This would be very nice :-)

Thx

**Comment by GtX-Andy** [comment]
Hi, yes the ***Fill Level Limiter*** will soon be returning to Farming Simulator 22 👍
