### ISSUE TITLE
Teleporter mode bugs vehicles occasionally

### ISSUE THREAD

**Issue by KITT3000** [GtX-Andy/easyDevelopmentControls#24]
I noticed that when teleporting vehicles (especially with attached tools, eg. weight), the non-flat positions of the machine jam under the ground. This does not always happen, but I would suggest adding, eg. 0.5m to the Y axis, to prevent this from happening.

**Comment by GtX-Andy** [comment]
Hey,

I will see how it performs with a little more height offset added. I already add ***1*** to the Y axis. I will need to make sure that adding more offset does not cause issues when there is many trailers attached. :-)

Cheers
