### ISSUE TITLE
Lower maxRunningSpeedMultiplier

### ISSUE THREAD

**Issue by VenoushCZ** [GtX-Andy/easyDevelopmentControls#25]
Hi! Would it be possible to add lower multipliers for <maxRunningSpeedMultiplier>? Like 1.2x or 1.5x?

Thank you for your work!

VenoushCZ

**Comment by GtX-Andy** [comment]
Hey VenoushCZ, 

I will see what I can do in the next feature update. The default running speed 1x (off) is rather slow though this is why I started at 2x.

Maybe it would be better to allow changes to the ***walk speed*** instead?

I can look at these options in the future however I have no timeline at this stage for the update that will include new features.

The next release will probably be just for small bugs if reported and translations.

Cheers 👍

**Comment by VenoushCZ** [comment]
Hi Andy,

The idea behind it was to get the running speed while being administrator back to the level of non-admin :-).

V.
