### ISSUE TITLE
Quality of life: Remember last setting for fill types

### ISSUE THREAD

**Issue by GMNGjoy** [GtX-Andy/easyDevelopmentControls#29]
## Successful use case
1. Launch game
2. F12, Spawn a bale (any type) 
3. hit ESC
4. Confirm proper Bale spawned.
5. F12 again.

### Expected & Actual
Previous bale setting are saved, you can spawn another bale of same type

## Unsuccessful use case
1. Launch game, get a tractor with a trailer
2. F12, Select a fill type / method / amount for the trailer, and fill said trailer
3. hit ESC
4. Confirm trailer with expected amount
5. F12 again.

### Expected result
Previous fill type and amount saved, and able to full again with same fill type

### Actual result
Previous Fill type no longer selected
Previous Fill method (Fill / Empty / Set) _still selected_
Previous Fill amount (if using Set method) value is gone 

Note - all other similar EDC items (`Add Bale`, `Add Pallet`, `Tip to Ground`) work this way, but the `Fill Level` tool does not.

**Comment by GtX-Andy** [comment]
Hey,

Thanks for the detailed information.

You will be happy to know that my good friend  **`Alien Jim`** also mentioned this to me a couple weeks ago and I fixed the typo stopping this from working in the update I submitted to modHub on the weekend 😀

Keep in mind the setting will be cleared once the user exits the vehicle or moves away from it and then uses the menu again as there is no guarantee the next vehicle will support the same fill types or have matching fill type index's 👍 

Cheers.
