### ISSUE TITLE
Change default key to F11

### ISSUE THREAD

**Issue by MattContassot** [GtX-Andy/easyDevelopmentControls#30]
I suggest change the default key from F12 to F11 like in FS19, that's because F12 is the default key for screenshot in Steam, so that is a little annoying...

**Comment by GtX-Andy** [comment]
Unfortunately the key binding `F11` is no longer available for use anymore when a user has the development console activated.
Giants now use the `F11` key binding to display the reflection maps.

As EDC is designed mainly as a mod testing creation tool most users will have the `Development Console` active so they can check their log files or use the other `F key` features, making `F12` the next best option.

You can however change the key binding to `F11` from the controls screen inside the game if this works better for you.

Hopefully that explains why F12 is now used 😃
