### ISSUE TITLE
Strong Farmer Default

### ISSUE THREAD

**Issue by CaptMike1** [GtX-Andy/easyDevelopmentControls#31]
Is there any conversation on editing the player strength to default to on? Turning it on each session is just an added task.

**Comment by KITT3000** [comment]
The settings are saved in `Documents/My Games/FarmingSimulator2022/modSettings/FS22_EasyDevControls/` but from what I can see so far there is only running speed and jump, so you probably have to wait for @GtX-Andy to add an option for strength.

**Comment by GtX-Andy** [comment]
As @KITT3000 has mentioned at this stage Super Strength is not saved. I did this as it can cause problems for many players especially if you forget this is enabled when starting a game. 😁 

I may look at adding this as an option for saving in a future update but I do like to limit settings etc as it takes away from the main goal of being a testing dev tool and adds more things I need to synchronise in Multiplayer and so on 😃
