### ISSUE TITLE
Bug: FillUnit not filling completely (in specific circumstances)

### ISSUE THREAD

**Issue by jtsage** [GtX-Andy/easyDevelopmentControls#36]
In the specific instance of the "limited trailer mass" setting being __ON__

![2022-09-12 20_54_50-Farming Simulator 22](https://user-images.githubusercontent.com/605986/189784115-d74f8089-81e0-4052-9ce2-c5083358125a.png)

__AND__ a fillUnit that has `updateMass="false"`

![2022-09-12 20_56_15-XTS446 xml - fs2022_workspace (Workspace) - Visual Studio Code](https://user-images.githubusercontent.com/605986/189784222-adb6bce9-1c66-45b5-8cad-6b503bd8ac08.png)

Easy Dev will only fill to the level that would have hit the maximum allowed mass if `updateMass` was true.  I missed this as well with simpleInspector, I was still doing the math, leading to overly inflated fill level percentages (https://github.com/jtsage/FS22_simpleInspector/issues/17)

**Comment by GtX-Andy** [comment]
Hey,
I am a little confused with what you are saying is the issue 🤔 

`updateMass` is not related to the `Trailer Fill Limit` so not sure how this is causing issues. `updateMass="false"` will just tell the FillUnit specialisation to not update the weight of the vehicle to include the crop or fill type that is added to that fill unit.

If you want a vehicle to ignore the `Trailer Fill Limit` then you would need to use `ignoreFillLimit="true".

You can check the state of this using `fillUnit.ignoreFillLimit` and the state of the setting using `g_currentMission.missionInfo.trailerFillLimit` 😄 

Maybe I misunderstand your report but with my testing the feature appears to be working correctly.
When `ignoreFillLimit` is true the trailer will be filled 100% no matter the weight of the crop added and when this is false the trailer is only filled to the maximum permitted limit for that vehicles components.

Cheers,

**Comment by jtsage** [comment]
Sorry, you are totally correct in what you said, with `ignoreFillLimit` true, easy dev does exactly what I expected and fully fills the implement in question. (For reference, I'm playing with the Kubota Equipment Pack by Iconik).

In this pack, the big sprayer has an XL mode (image above), where `ignoreFillLimit` is left to the default (false), and `updateMass` is set to true - filling with easy dev sets the fill to somewhere in the range of 5000 liters (which corresponds to the amount that would fit vs. the available mass space).  However, if I drive it over to a pallet of fertilizer or a fill trigger, the game allows me to fill it to the complete capacity of 15000 liters.

I'm not sure the behavior of easy dev is wrong here - looking through the base game files, `updateMass` is not taken into account in conjuction with `Trailer Fill Limit` - from a pure logic standpoint, it makes sense that if the filltype weights nothing, I should be able to put as much in there as I want to (up to the real capacity), but giants also gave us `ignoreFillLimit`, which should be true in this case - it's really a bug with the mod, and indeterminate behavior on the part of the game.

Hope that my rambling makes some sense above - thanks!
