### ISSUE TITLE
Added Slurry has wrong N/M3

### ISSUE THREAD

**Issue by MRNOBODY515** [GtX-Andy/easyDevelopmentControls#37]
Hey Andy. When adding Slurry to a Slurry Tanker it will shows -4 kg N/m3 when playing with precision farming. So this would mean the Slurry has a negative Nitrogen value.

**Comment by GtX-Andy** [comment]
Hi, I am sorry I completely missed this 😱 

I have not done any testing with PF, I will have a look and see why this may be the case.
Sometimes some scripts just do not like fill level changes in the way EDC does it...

Thanks...
