### ISSUE TITLE
Super strength doesn't work anymore with patch 1.8.1.0

### ISSUE THREAD

**Issue by aurelien2023** [GtX-Andy/easyDevelopmentControls#38]
Super strength doesn't work anymore with patch 1.8.1.0
"LumberJack" from loki_79 doesn't work either...

**Comment by GtX-Andy** [comment]
I have released a Hot Fix [HERE](https://github.com/GtX-Andy/easyDevelopmentControls/releases/tag/V1.2.0.2-hotfix) available 👈  for the super strength issue..

I will be uploading a new feature update soon that fixes some other small bugs introduced by the latest game update along with a couple previous bug fixes and some new features.

Cheers 🍻
