### ISSUE TITLE
Translation Italian

### ISSUE THREAD

**Issue by Rudolfet** [GtX-Andy/easyDevelopmentControls#41]
Hello,

i send you the Italian Translation
[easyDevelopmentControls_l10n.zip](https://github.com/GtX-Andy/easyDevelopmentControls/files/10048091/easyDevelopmentControls_l10n.zip)

Thanks for regarding

**Comment by GtX-Andy** [comment]
Translation file is now available here on GitHub and will be included very soon to the Giants ModHub release 😃 
Thank you it is great to have Italian added to the translations ❤️
