### ISSUE TITLE
Question on flipping

### ISSUE THREAD

**Issue by judg393** [GtX-Andy/easyDevelopmentControls#42]
The in game modhub description states its possible to flip vehicles using EDC how? is this a one button key stroke to right vehicles? or are you referring to the use of super strength?

**Comment by GtX-Andy** [comment]
There is a button on the third column of the **GENERAL** page called **Flip Vehicles**.

When you are in a vehicle or next to vehicle this button will become available. When pressed this will correct the vehicles placement.

Note: If you have loose items such as logs, bales or pallets you may find these will not be moved with the vehicle just as with teleporting vehicles. 😉

**Comment by judg393** [comment]
I feel so blind thanks. Also thanks for the warning on straps yeah it's not a happy bunny when you've got logs strapped. 

Not sure if this is feasible but what are the chances you can find a way to refresh sales xml through edc? I tried refreshing the store but that didn't work for changing up sales 

Any way thanks for fixing my blindness

**Comment by sashaman** [comment]
sales is kinda time based 
try to edit to your liking 
[FS22_salesBalance.zip](https://github.com/GtX-Andy/easyDevelopmentControls/files/10238984/FS22_salesBalance.zip)

**Comment by GtX-Andy** [comment]
I have added your refresh sales request to the list for a future update when possible.
