### ISSUE TITLE
Easy Development Control

### ISSUE THREAD

**Issue by Mr1960fredi1** [GtX-Andy/easyDevelopmentControls#45]
Ich habe die letztgültige Version heruntergeladen und in den Mod Ordner des LS22 verschoben. Im Mod Ordner (Explorer) ist die Zip Datei enthalten, im Spiel scheint aber der Mod nicht auf? In der game.xml ist der Konsolenbefehl enthalten und auf true geändert. 
Scheint aber im Spiel nicht auf.
Ich habe mittlerweile das Spiel neu installiert und mehrfach repariert, erfolglos.
Bitte um Info was ich machen kann, dass der Mod im Spiel integriert ist, und auch aktivierbar.
Danke im Voraus

[Game_xml.pdf](https://github.com/GtX-Andy/easyDevelopmentControls/files/10253467/Game_xml.pdf)

**Comment by sashaman** [comment]
deinen LS auf die aktuellste version aktualisieren 
UPDATE 1.8.2.0 (14. NOVEMBER 2022)

**Comment by sashaman** [comment]
p.s.: die game.xml bringt gar nix, die log.txt ist die datei die eigentlich jeder braucht um helfen zu können
