### ISSUE TITLE
Feature Request Include Custom Fields

### ISSUE THREAD

**Issue by GarrettHafen** [GtX-Andy/easyDevelopmentControls#49]
How hard would it be to change the EasyDevControls:setFieldFruit function, and others, to either allow for a nil field index and instead of throwing an error, searching for a target field? just adding "Target" as an option in the Set Field Fruit menu. This would allow custom fields to be included with these controls. I assume. I'd do it my self if I had the ability but I don't.... so here I am. 

I'm thinking that CoursePlay can create accurate field boundaries for custom fields, and the map knows about custom fields, and you can see the stats of a custom field, so it begs the question: Is it possible to get EDC to recognize custom fields. 

#easierSaidThanDone
Love your work!

**Comment by StevenT72** [comment]
2nd this. Would like custom fields.

**Comment by GtX-Andy** [comment]
I have played with the option to set custom fields in the past. I have just not had the time to find a good solution suitable for all situations.

It is on my list of things to do so it could show up in an update soon, you never know.
Thanks for the request 👍
