### ISSUE TITLE
Superstrength not available in F12 menu 

### ISSUE THREAD

**Issue by GmanAtheist** [GtX-Andy/easyDevelopmentControls#51]
Superstrength not available in F12 menu . FS22 . It says it is disabled.  Please help.

**Comment by GmanAtheist** [comment]
OK. So incompatible with lumberjack. I need Lumberjack. Please fix. Thanks.

**Comment by GtX-Andy** [comment]
Hi, Super Strength is disabled when Lumber Jack mod is active as it already has a super strength feature using a 'key binding'
It is disabled so there is no conflict between the mods.
