### ISSUE TITLE
Feature Request: Button for toggling "needs plowing" state

### ISSUE THREAD

**Issue by Timmeey86** [GtX-Andy/easyDevelopmentControls#52]
Since several map/mod combinations have issues where a ready-to-harvest NPC field claims that it requires plowing, and the game always generates a plowing instead of a harvesting mission in that case, it would be helpful to have a button which allows you to only toggle the "needs plowing" state of a field, without changing anything else (like fertilization state etc)
Currently, this can be done by setting the fruit type, but you need to set a lot of other settings to your best guess of the field state

**Comment by GtX-Andy** [comment]
Request noted for potential inclusion in a future update 👍
