### ISSUE TITLE
Failed fill

### ISSUE THREAD

**Issue by seanwhyte2306** [GtX-Andy/easyDevelopmentControls#53]
Hey guys,

The mod cotton picker 770 says failed fill when I try to fill the vehicle.
No errors in the log
What would be the issue?

**Comment by GtX-Andy** [comment]
Hi, It is not possible to fill a round baler using Easy Development Controls or a console command as it causes issues with the bale animations and creates errors.

So unfortunately this cannot be changed at this time sorry.
