### ISSUE TITLE
Password Protection?

### ISSUE THREAD

**Issue by oli3010** [GtX-Andy/easyDevelopmentControls#54]
Hi 
first i want to say thanks to this great Mod. 
now my question, is ist possible to add a password protection in your mod?
We use your Mod in many Multiplayer projects,
every one knows the admin password, they need it to save the game. 
unfortunately use some Player this Mod to cheat ,
that was Not the way we would use your mod. 
a password should stop this maybe 

grettings 
Oli

**Comment by NathanS-8500** [comment]
Sounds like a good idea. I guess we will have to wait and see!

**Comment by MeRida2104** [comment]
If your mate logged in as admin, he can use cheats anyway if he has activated the console. So a password feature won't prevent them from using cheats.

**Comment by GtX-Andy** [comment]
Request noted for potential inclusion in a future update however this will be low priority for FS22 as it requires a large amount of changes to implement correctly and would not necessarily solve the issue.

There may be the possibility to limit access to some admins but this will need to be reviewed.

Unfortunately stopping people from cheating that are logged in as **Admin Users** is difficult as mentioned by @MeRida2104 

A better option would be for Giants to allow **Farm-Managers** to save the game by default.

This is a possible option that I could add to the next update, any user can make a save request using the in-game **chat**, for example **/save**, and if this was not executed in the last 15min then save the game. This way there is no need to give all your players admin rights so they can save the game allowing for more control over console commands and EDC
