### ISSUE TITLE
Possibility to capture and export tire tracks

### ISSUE THREAD

**Issue by VenoushCZ** [GtX-Andy/easyDevelopmentControls#55]
Hi! Is there a possibility to record/capture/save to i3d the dynamically created tire tracks during the gameplay so that it can be used as a placement mod later? The fact that the beautifully "used" yard is always reset each time the game starts always bothered me.

V.

**Comment by GtX-Andy** [comment]
Unfortunately this is not supported by the game Tyre System at this stage sorry. Maybe in a future game release 😁 🤞
