### ISSUE TITLE
Not saving preferences

### ISSUE THREAD

**Issue by rogeriodec** [GtX-Andy/easyDevelopmentControls#57]
Sorry, it must be a basic question, but every time I load FS22, the preferences changes I made to your mod are lost, and I have to redo everything again.
Is there any way to save these preferences to be fixed in all FS22 sessions?

**Comment by GtX-Andy** [comment]
I am not sure what settings you are losing each time you load so I cannot comment totally but I will try and explain.
As Easy Development Controls is intended to be used for mod creation and debugging not all settings are saved as this could introduce issues and this would not be helpful. 😂 

In the current release the only settings that are saved are as follows:

1. Hud Input **{General Page}**
2. Extra Timescales **{General Page}**
3. Running Multiplier Speed **{Player Page}**
4. Running Multiplier Key **{Player Page}**
5. Jump Multiplier **{Player Page}**

Other options such as **Super Strength** for example are not saved as they can cause issues when left enabled and **Wood Cutting Marker** disabled for example could cause confusion if it is missing and the user has forgotten they disabled it.

If your question is about carrying your settings over to new save games and MP sessions then you can adjust the *defaultUserSettings.xml** located at **C:\Users%USERNAME%\Documents\My Games\FarmingSimulator2022\modSettings\FS22_EasyDevControls** for the above 5 settings.

This will then be used for all new save games and when joining a Multiplayer game (Subject to admin preferences)
