### ISSUE TITLE
Forditsa le a rendszer nyelv használatához!

### ISSUE THREAD

**Issue by BGERYP** [GtX-Andy/easyDevelopmentControls#58]
translation_en for hu.

**Comment by GtX-Andy** [comment]
Hi 👋 

I am happy to include translations to other languages as submitted by the community that are error free in game and 100% complete.

Unfortunately I do not speak, read or write all the languages available in the world so I can only add these when they are supplied to me. 😁 

If you would like to issue a **Pull request** here on GitHub for the **Hungarian (hu)** translation or send me a link here as an **issue** to the XML file on _**dropbox**_, _**oneDrive**_, _**googleDrive**_ or _**[workuploaded](https://workupload.com/)**_ I will add this in the next update.

I will always prioritise the updating of a mod when a new translation is available as I want the whole community to enjoy the mod.
