### ISSUE TITLE
Set crop with a farmid higher than 8 farms not possible

### ISSUE THREAD

**Issue by MeRida2104** [GtX-Andy/easyDevelopmentControls#59]
Hello, I have found that set the crop feature does not work if the field belongs to a farm whose farmid is higher than 8. Could u please add this feature in one of the next updates?

At the moment our workaround is to sell the field, buy it with a farmid lower than 8, set the fruit. After that we have to sell it again and buy it with the initial farm.

**Comment by GtX-Andy** [comment]
As the base game only supports 8 farms this was the reason for the limit as higher ranges would never have been used.

I do not normally adjust for mods, as you can understand there are so many so it would leave no time for anything else 😂 
However this should not be too hard so your request has been noted for potential inclusion in a future update.
