### ISSUE TITLE
Question: Disable 4x Running Speed if admin

### ISSUE THREAD

**Issue by MeRida2104** [GtX-Andy/easyDevelopmentControls#62]
Hey, I'd to disable the feature, that any Admin in Dedicated Server automatically has 4x running speed. Where can I deactivate this?

thx und best regards

**Comment by GtX-Andy** [comment]
When a player joins a Multiplayer game their default settings are loaded from the **defaultUserSettings.xml** located at **C:\Users\%USERNAME%\Documents\My Games\FarmingSimulator2022\modSettings\FS22_EasyDevControls** unless the server permissions do not allow this. (Configurable on the Permissions page)

However no users running speed should be active without pressing the 'Key binding' or changing this to active in the F12 menu after game load.

If you wish to remove the permission from **Admins** this is not possible as these should be your trusted crew only and if you do not want them to use this feature then hopefully you can just make this rule...

Have fun 👍
