### ISSUE TITLE
Precision Farming

### ISSUE THREAD

**Issue by iampincio** [GtX-Andy/easyDevelopmentControls#64]
Good morning, using this mod I noticed that creating crops in the fields with fertilizer etc. in the precision farming maps does not change anything. is it just my problem? will you fix it in the next version of the mod?

**Comment by GtX-Andy** [comment]
Hey 👋

Precision Farming changes so many things that I am sure there is certain features in EDC that will not be set correctly.
I have intended to add a dedicated page for 'Precision Farming' to allow easier testing when using it but this was not high on the list to date.

I do not normally add extended support for other mods as there is so many it is just not possible to keep up unless the mod relies on them or is a good pairing. I do make exceptions for Giants mods though and DLC's.

I have made a note of the issue and will do some testing and see what I can do in a future update 😉

**Comment by iampincio** [comment]
Very big thanks!

Il giorno ven 10 nov 2023 alle 07:41 GtX ***@***.***> ha
scritto:
