### ISSUE TITLE
Can't use the mods

### ISSUE THREAD

**Issue by ilansupernova** [GtX-Andy/easyDevelopmentControls#67]
Hello, i download your mods like 40 times... but i just can't use it. The mod appear in the installed list in the game menu, it is in the mods file list but it doesnt appear in the mods selection page at the start of a game and it can't be started in the game.
Can someone help me ?

**Comment by KITT3000** [comment]
Show game log (Documents/My Games/FarmingSimulator2022/log.txt)

**Comment by ilansupernova** [comment]
> Show game log (Documents/My Games/FarmingSimulator2022/log.txt)

It says that : '' Error: Invalid mod name 'FS22_EasyDevControls (3)'! Characters allowed: (_, A-Z, a-z, 0-9). The first character must not be a digit''

**Comment by KITT3000** [comment]
Well, you could have corrected it instead of writing here without giving the log file I asked for...

**Comment by GtX-Andy** [comment]
This seems like a non issue where Windows has renamed the file when downloading..  Thank you very much @KITT3000  for assisting!!
