### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Michaelj15** [GtX-Andy/easyDevelopmentControls#68]
Hello Andy,

Is it possible to make a shortkey for switching the third person on and off, so you don't have to open the edc menu?

Thanks!

**Comment by GtX-Andy** [comment]
Hello,

Sorry for the late reply. Although I have new features I wanted to add to this release of EDC I have not had the time so far in the last 6 months.

With the third person mode this was purely added to allow screenshots to be created by easily allowing access to the base game console command. At this stage there is no plan to add a hot key but this may change for the next game release.

Have fun!
