### ISSUE TITLE
Possible conversion

### ISSUE THREAD

**Issue by M5Competition** [GtX-Andy/easyDevelopmentControls#69]
Slightly off topic but would you ever consider converting the Animal pen extension mod to fs22? was a fantastic mod and cant seem to find any similar mod and it really feels like a missing mod to me on any playthrough, thanks.

**Comment by GtX-Andy** [comment]
Hi,

Sorry for the late reply..  I have been very busy with real life so many of the mods I would have released by now have been delayed. When it comes to old mods I have released I do not like to just move them from one game version to the next without bringing them up to the new standard or improving them as required, keeping them fresh and enjoyable and this does take time.

I do not think I will be bringing the function of Animal Pen Extension to FS22 but I have not ruled it out for the next game release 😃 

I am glad you enjoyed the mod, this makes me happy to hear 😊 . I have a number of plans for the next game release so lets see what the next game brings soon I am sure!

**Comment by M5Competition** [comment]
Hello andy have you thought anymore about the animal pen extension mod? it is the only mod i keep looking for as i hate manually feeding animals 😆 , thank you
