### ISSUE TITLE
error in log when using super stregth

### ISSUE THREAD

**Issue by Alan07826** [GtX-Andy/easyDevelopmentControls#71]
hi getting an error in server log when using super strength, same with different users in game, can activate it no bother,, but as soon as move an object server log goes mad repeating error

2024-02-06 10:00 Error: Running LUA method 'update'.
dataS/scripts/player/Player.lua(3110) : attempt to perform arithmetic on local 'inputValue' (a nil value)

**Comment by Iwan1803** [comment]
Same here and no solution...
Looks like the mod is "dead".

**Comment by GtX-Andy** [comment]
It seems you may be using an old outdated version or there is a mod/script conflict. I am aware of 3 personal servers at time of writing using the Super Strength feature of this mod with no issues.

Do make sure you are using the latest official release available at the link below.  If you are still experiencing the issue after doing so then you may have a mod conflict where another script is also making changes causing this issue.

You can try and locate the conflict by disabling all script mods and then enable them in small groups until the problem mod is found and then remove it 😃 

[🎁 Latest Official Download Link](https://www.farming-simulator.com/mod.php?&mod_id=244313&title=fs2022)
