### ISSUE TITLE
Stop Time issue.

### ISSUE THREAD

**Issue by MetalHeadSeven** [GtX-Andy/easyDevelopmentControls#8]
If I save and exit with time stopped the save will stop loading at 50%.  I then have to exit and load with easyDevelopmentControls disabaled.

**Comment by GtX-Andy** [comment]
Hey @MetalHeadSeven thank you for taking the time and reporting this issue. 👍 
I will make some adjustments tonight and add a beta version here that can be used while waiting for the ModHub update.

**Comment by MetalHeadSeven** [comment]
You're welcome happy to help easyDevelopmentControls is one of my favorite Mods.  Thanks for all your work on it,

**Comment by GtX-Andy** [comment]
@MetalHeadSeven If have not seen there is now a beta release that solves this issue available here [Beta Release](https://github.com/GtX-Andy/easyDevelopmentControls/releases/tag/V1.0.1.0-beta)

Thanks again for reporting the issue :+1:

**Comment by MetalHeadSeven** [comment]
Thanks for the quick fix. It works perfectly now.

**Comment by GtX-Andy** [comment]
Great 👍
