### ISSUE TITLE
LUA error on Multiplayer Dedicated server

### ISSUE THREAD

**Issue by Dubs73pp3r** [GtX-Andy/easyDevelopmentControls#81]
Added mod to dedicated server through Nitrado, checked logs when couldn't load into game and saw this repeating error.

2024-11-17 16:11 Error: Running LUA method 'update'.
profile/mods/FS25_EasyDevControls/scripts/main.lua:93: attempt to call missing method 'showYesNoDialog' of table

**Comment by mozic** [comment]
> Added mod to dedicated server through Nitrado, checked logs when couldn't load into game and saw this repeating error.
> 
> 2024-11-17 16:11 Error: Running LUA method 'update'. profile/mods/FS25_EasyDevControls/scripts/main.lua:93: attempt to call missing method 'showYesNoDialog' of table

You see I don't think it's been officially released for FS25 yet. I came here looking for some news/updates but everything says FS22 still.

**Comment by Dusty-Lane** [comment]
It for sure has not been converted by Andy.  Dont download any mod from weird sources, especially script mods.

**Comment by GtX-Andy** [comment]
Hey,

As @Dusty-Lane  has said I have not yet released a Farming Simulator 2025 version of this mod or any of its function.

Any releases or conversion attempts are illegal and done without permission from me.. 
Mods officially released and supported by myself are only available via the [Giants ModHub](https://www.farming-simulator.com/mods.php?title=fs2025&filter=org&org_id=129652&page=0) or [GitHub](https://github.com/GtX-Andy)

Please use caution when downloading mods from other sites especially when they are script mods as they can contain viruses or completely delete your save games as witnessed in FS25 by some dodgy mods.

There will be an official FS25 release of Easy Development Controls coming soon.

Keep an eye out for releases at one of the following links...
[GitHub Repository](https://github.com/GtX-Andy/fs25_easyDevelopmentControls)  and  [GtX FS25 ModHub](https://www.farming-simulator.com/mods.php?title=fs2025&filter=org&org_id=129652&page=0)

I wish everyone a great Christmas and New Year...

GtX | Andy
